language: csharp
mono: latest
dotnet: 2.2.401
install:
  - msbuild -t:Restore -p:Configuration=Release
  - nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner
script:
  - msbuild MonoDevelop.MSBuildEditor.sln -p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./MonoDevelop.MSBuild.Tests/bin/Release/MonoDevelop.MSBuild.Tests.dll
